# Generated by Django 2.0.5 on 2018-07-11 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.TextField()),
                ('custom_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Scrumy Goals',
            },
        ),
        migrations.CreateModel(
            name='ScrumyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Scrumy Status',
            },
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='scrumy_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrumy.ScrumyStatus'),
        ),
    ]
