# Generated by Django 2.0.5 on 2018-07-12 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumy', '0004_scrumystory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumygoals',
            name='custom_user',
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='scrumy_story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scrumy.ScrumyStory'),
            preserve_default=False,
        ),
    ]
