# Generated by Django 2.0.5 on 2018-07-13 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumy', '0005_auto_20180712_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumygoals',
            name='scrumy_story',
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='scrumy_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
