# Generated by Django 2.0.5 on 2018-07-13 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumy', '0006_auto_20180713_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumygoals',
            name='scrumy_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumy_status', to='scrumy.ScrumyStatus'),
        ),
        migrations.AlterField(
            model_name='scrumygoals',
            name='scrumy_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrumy_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
